const myDiv = document.getElementById("myDiv");
myDiv.style.backgroundColor = "yellow";
myDiv.style.margin = "20px";
myDiv.style.padding = "10px";
myDiv.style.fontSize = "18px";
myDiv.style.fontWeight = "bold";
myDiv.style.height = "200px";
myDiv.style.width = "300px";
myDiv.style.color = "blue";